title: Calvin Cheng
author: Calvin Cheng
email: calvincheng919@gmail.com
description:

My Description.

# social links
twitter_username: calvincheng919
github_username:  calvincheng919

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
