title: calvin cheng
author: Calvin Cheng
email: calvincheng919@gmail.com
description:  # this means to ignore newlines until "baseurl:"
 test

# social links
twitter_username: calvincheng919
github_username:  calvincheng919

show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
 - about.md

theme: minima
