title: Calvin Cheng
#author: calvin cheng
email: calvincheng919@gmail.com
description:  # this means to ignore newlines until "baseurl:"
 A yawn is a silent scream for coffee, and a sigh is a silent scream for beer

#social links
twitter_username: calvincheng919
github_username:  calvincheng919
linkedin_username: calvincheng

show_excerpts: false # set to false to remove excerpts on the homepage

header_pages:
 - portfolio.md
 - about.md

theme: minima

# Google Analytics
google_analytics: UA-122139025-5

plugins:
 - jekyll-seo-tag
