title: calvin cheng
author: Calvin Cheng
email: calvincheng919@gmail.com
description:  # this means to ignore newlines until "baseurl:"
 Thank you for visiting me here on Github. 
 I am a tinkerer... I tinker. 
 ex-IBM Cognos consultant; 
 ex-Amazon BI Manager; 
 ex-AWS Something; 
 Love Javascript

# social links
# twitter_username: calvincheng919
# github_username:  calvincheng919

# generate social links in footer
  social_links:
    twitter: calvincheng919
    github:  calvincheng919
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
 - about.md
 - projects.md

theme: minima
