title: calvin cheng
author: calvin cheng
email: calvincheng919@gmail.com
description:  # this means to ignore newlines until "baseurl:"
 I am a tinkerer... I tinker 

#social links
twitter_username: calvincheng919
github_username:  calvincheng919
linkedin_username: calvincheng

show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
 - about.md


theme: minima
